### ISSUE TITLE
缺少rollup依赖，手动安装后，却又提示“__name is not defined”

### ISSUE THREAD

**Issue by zzjjbbaa** [umbrella22/electron-vite-template#100]
缺少rollup依赖，手动安装后，却又提示“__name is not defined”

**Comment by umbrella22** [comment]
有没有可能，我的readme中说了要用yarn，但是你却用了pnpm

**Comment by zzjjbbaa** [comment]
> 有没有可能，我的readme中说了要用yarn，但是你却用了pnpm

已经解决，vite的bug

**Comment by liuyuu11** [comment]
> > 有没有可能，我的readme中说了要用yarn，但是你却用了pnpm
> 
> 已经解决，vite的bug

怎么解决的，我也遇到。yarn安装

**Comment by zzjjbbaa** [comment]
> 

 vite.build()中设置
keepNames: true,

**Comment by zzjjbbaa** [comment]
> > > 有没有可能，我的readme中说了要用yarn，但是你却用了pnpm
> > 
> > 
> > 已经解决，vite的bug
> 
> 怎么解决的，我也遇到。yarn安装

![image](https://github.com/umbrella22/electron-vite-template/assets/54572770/e4de2e9e-4928-4e5c-b5c6-4d08a889cdff)

**Comment by liuyuu11** [comment]
> > > > 有没有可能，我的readme中说了要用yarn，但是你却用了pnpm
> > > 
> > > 
> > > 已经解决，vite的bug
> > 
> > 
> > 怎么解决的，我也遇到。yarn安装
> > vite.conifg.ts中 添加
> > ![image](https://user-images.githubusercontent.com/54572770/255545109-e4de2e9e-4928-4e5c-b5c6-4d08a889cdff.png)

var __defProp = Object.defineProperty;
var __name = (target, value) => __defProp(target, "name", { value, configurable: true });
globalThis.__name = __name

我在其他的issue也看到这种解决方案了。但是我感觉这种方案很奇怪，不知道会不会有其他坑在。另外，我另外一台电脑 nodejs 16.17.0 + npm/yarn安装没问题。。这台电脑 nodejs 18.17.0 + yarn 就有这种奇葩问题

**Comment by umbrella22** [comment]
伙计们现在它可以正常工作了，不过当然使用的也是 @liuyuu11 的办法，不过我区分了环境，仅在开发时添加该方法，build命令下不会添加，测试已经完全通过，很高兴框架能够再次为你们服务，我为我之前的鲁莽言论感到抱歉
