### ISSUE TITLE
Error: Cannot find module 'rollup'

### ISSUE THREAD

**Issue by asd375zxcvb** [umbrella22/electron-vite-template#106]
dev-runner.ts文件里面报错没有找到'rollup'依赖，package.json里面也没有引入，在node_module里面也没有找到对应的依赖文件

![image](https://github.com/umbrella22/electron-vite-template/assets/38804714/694c0e1d-f1a0-42f5-948a-9d645ea31234)

**Comment by umbrella22** [comment]
你的yarn版本是多少呢，rollup是用了vite的依赖，是属于幽灵依赖来的，但是yarn1和npm都可以正常工作哦
