### ISSUE TITLE
preload.js 怎么构建出来？

### ISSUE THREAD

**Issue by tom-style** [umbrella22/electron-vite-template#108]
看 rollup.config.ts 倒有类型判断preload，但实际好像并有使用；

strict 分支和主分有什么不同？

**Comment by umbrella22** [comment]
strict分支主要是禁用了在渲染进程中使用主进程的任何能力，包含node的所有模块调用，你均只能使用[preload](https://www.electronjs.org/zh/docs/latest/tutorial/tutorial-preload)来给渲染进程提供这些方法，在将来的日子中，main分支也会改变成这样的形式，并最终和strict合并
