### ISSUE TITLE
没有开发文档吗

### ISSUE THREAD

**Issue by mouseheike** [umbrella22/electron-vite-template#110]
没看到vue3版本的开发文档

**Comment by mouseheike** [comment]
没有开发文档不敢用，害怕没更新

**Comment by mouseheike** [comment]
会持续更新吗，如果不持续更新也麻烦。

**Comment by mouseheike** [comment]
我咨询的是electron-vite-template这个的文档，不是指vue的文档。如果长期维护和文档齐全，可以贴出赞助二维码，支持一下

**Comment by umbrella22** [comment]
等同于 [vue-template](https://umbrella22.github.io/electron-vue-template-doc/) ，二者除去不需要关系的编译部分，主要功能是一样的

**Comment by umbrella22** [comment]
后续的话，文档会以vite这边为主，然后慢慢的淡化原来那个了，主要是懒癌发作不想改仓库了
