### ISSUE TITLE
打包后的node_modules比较大

### ISSUE THREAD

**Issue by boolter** [umbrella22/electron-vite-template#113]
刚刚开始接触electron  和前端有些不是很懂,引用了自己想要的相关node_modules,打包以后的node_modules体积稍微有点大, 看了一下是不是可以对node_modules进行处理一下,作者大大有没有比较好的方案,比如混淆压缩一下。

**Comment by umbrella22** [comment]
关于node_modules问题参考[此处](https://umbrella22.github.io/electron-vue-template-doc/essentials/build)
