### ISSUE TITLE
strict 分支，npm run build:web 构建之后的产物还是依赖 electron 

### ISSUE THREAD

**Issue by wangyesheng** [umbrella22/electron-vite-template#121]
![image](https://github.com/umbrella22/electron-vite-template/assets/42696348/4035c782-6078-4d93-9aa8-ba9f2ba3119f)
![image](https://github.com/umbrella22/electron-vite-template/assets/42696348/3cdd43cc-e3d0-4584-927a-c5da2c35bb63)

**Comment by umbrella22** [comment]
挠了挠头，代码是最新的吗？strict分支测试web是可以的啊

**Comment by wangyesheng** [comment]
> 挠了挠头，代码是最新的吗？strict分支测试web是可以的啊

对的，代码是最新的😥

**Comment by umbrella22** [comment]
我新增了一个mini-main分支，这里的话，是完全ok的，严格分支我还在看问题

**Comment by wangyesheng** [comment]
> 我新增了一个mini-main分支，这里的话，是完全ok的，严格分支我还在看问题

谢谢！😘
