### ISSUE TITLE
如何定位打包之后的问题？

### ISSUE THREAD

**Issue by l8oo8l** [umbrella22/electron-vite-template#123]
开发过程中一直使用的dev模式，现在打包了，突然白屏看不到信息了，把vue-devtools打开了也是白的，好像没有加载到renderer的内容，再main模块加了electron-log，看到是加载完成了，刚使用半个月，还不熟，有没有什么方式可以去定位的？

**Comment by umbrella22** [comment]
渲染进程白屏你可以用sentry去收集error信息，而且如果你在渲染进程去调用node，然后出现崩溃也会导致白屏
