### ISSUE TITLE
tsconfig.json vscode编辑器报错

### ISSUE THREAD

**Issue by caisededan** [umbrella22/electron-vite-template#127]
![image](https://github.com/umbrella22/electron-vite-template/assets/144215768/34ed06cf-969a-422a-8e39-00847c6e7aa6)
查了一下是 "types": ["vite/client"] 没有在 "typeRoots": ["node_modules/@types"] 根路径下，
改为 "typeRoots": ["node_modules"]，就没有报错了
不知道这样改有没有性能问题，作者可以看看有没有其它修复办法

**Comment by umbrella22** [comment]
这个我稍后修复，因为升级了vite5没有关注类型错误，大概今晚修复，这样也没有性能问题
