### ISSUE TITLE
打包后字体图标不生效问题

### ISSUE THREAD

**Issue by a-cool-boy** [umbrella22/electron-vite-template#130]
运行字体图标正常显示，打包后字体图标不生效了，可能是文件路径问题？但我对electron还不是很熟悉，特来求助，望不吝赐教！

**Comment by mlmdflr** [comment]
百分之八十是路径问题，但还是请你贴图代码或者建一个示例的demo仓库放上来

**Comment by a-cool-boy** [comment]
> 百分之八十是路径问题，但还是请你贴图代码或者建一个示例的demo仓库放上来
你好 以下是字体图标使用相关代码 /iconfont目录是字体图标相关文件
// 页面中使用
<template>
  <a-space>
    <icon-font type="icon-tuichu" />
  </a-space>
</template>
<script lang="ts" setup>
import { createFromIconfontCN } from '@ant-design/icons-vue';

const IconFont = createFromIconfontCN({
  scriptUrl: '../assets/iconfont/iconfont.js', // 引入字体图标路径
});
</script>

**Comment by a-cool-boy** [comment]
> 百分之八十是路径问题，但还是请你贴图代码或者建一个示例的demo仓库放上来
你好 以下是字体图标使用相关代码 /iconfont目录是字体图标相关文件
// 页面中使用
<template>
  <a-space>
    <icon-font type="icon-tuichu" />
  </a-space>
</template>
<script lang="ts" setup>
import { createFromIconfontCN } from '@ant-design/icons-vue';

const IconFont = createFromIconfontCN({
  scriptUrl: '../assets/iconfont/iconfont.js', // 引入字体图标路径
});
</script>

**Comment by a-cool-boy** [comment]
> 百分之八十是路径问题，但还是请你贴图代码或者建一个示例的demo仓库放上来
码云demo: https://gitee.com/qianmo_xx/electron-test.git

**Comment by mlmdflr** [comment]
> > 百分之八十是路径问题，但还是请你贴图代码或者建一个示例的demo仓库放上来
> > 你好 以下是字体图标使用相关代码 /iconfont目录是字体图标相关文件
> > // 页面中使用
> 
> <script lang="ts" setup> import { createFromIconfontCN } from '@ant-design/icons-vue';
> const IconFont = createFromIconfontCN({ scriptUrl: '../assets/iconfont/iconfont.js', // 引入字体图标路径 }); </script>

很显然是路径问题，这个不是electron的问题，是vite的基础问题
![image](https://github.com/umbrella22/electron-vite-template/assets/93173537/94c5e087-934f-440a-b528-556ada959219)
你这个图标的代码放在assets路径下是不会被打包进来的

解决：
你只需要将需要的图标代码按照一个个文件夹的方式统一放在public路径下，在这样如图这样设置路径即可
![image](https://github.com/umbrella22/electron-vite-template/assets/93173537/d0b0a8a0-d385-4c7e-abcb-7810ebae971f)
通过import.meta.url就可以解决生产开发环境路径不一致的问题

效果：
![image](https://github.com/umbrella22/electron-vite-template/assets/93173537/9a221785-e1e3-4afb-870d-284793a200e1)

参考：
vite文档  https://cn.vitejs.dev/guide/assets.html#the-public-directory
没事多看看

**Comment by a-cool-boy** [comment]
@mlmdflr 多谢
