### ISSUE TITLE
安装完第一次运行腾讯电脑管家报注册表问题

### ISSUE THREAD

**Issue by 1438343098** [umbrella22/electron-vite-template#135]
这段代码有修改空间吗
![image](https://github.com/user-attachments/assets/403410a2-922a-4083-9c80-78a6dafdf8bd)

**Comment by umbrella22** [comment]
没有，这段代码意为注册协议，如果你不需要可以直接删掉，他的作用就类似百度网盘，和qq在网页状态下拉起应用的一个实现
