### ISSUE TITLE
安装 electron-vite-template 模版，启动 dev 模式后会报错

### ISSUE THREAD

**Issue by wubaiqing** [umbrella22/electron-vite-template#136]
NodeJS 版本：v18.19.1
系统：Mac Sonoma 14.6.1

依赖在正常安装的情况下，使用 electron-vite-template 模版后，页面报错：

**报错信息如下**
全局面板错误：
<img width="1045" alt="image" src="https://github.com/user-attachments/assets/aad8ff72-284f-4cf0-b90c-876b467badf2">

展开一：
<img width="1045" alt="image" src="https://github.com/user-attachments/assets/b28efa3c-2dc8-4940-88c1-cc08d29f18d3">

展开二：
<img width="1045" alt="image" src="https://github.com/user-attachments/assets/9061d73d-eb1f-4e0b-ab70-5c446216d38c">

**Comment by mlmdflr** [comment]
已经修复了，这个问题出在IpcChannelMainClass和IpcChannelRendererClass的类型声明上，如果不设定默认值，则直接实例化的时候是一个空的对象（{}），请在我的pr通过的时候重新拉取项目，或者直接修改src下的ipc文件夹下得channel.ts文件，为每个属性设置一个默认值
![image](https://github.com/user-attachments/assets/f5775c41-1de1-4466-9e8a-e3a98681967a)

**Comment by umbrella22** [comment]
#137 close
