### ISSUE TITLE
启动了服务 但是调接口就是404

### ISSUE THREAD

**Issue by c1999** [umbrella22/electron-vite-template#138]
启动了服务 但是调接口就是404

**Comment by umbrella22** [comment]
不是哥们这么抽象的吗，图呢，我哪知道你启动了什么服务- -。。。。你问你后端啊，你问我啊认真的吗

**Comment by c1999** [comment]
啊 我是用的之前的版本内置的express启动的服务 然后不是还有个调用/message的方法 请求本地启动的接口嘛 调不通

**Comment by c1999** [comment]
如果我想用内置的express 有什么办法解决吗

**Comment by c1999** [comment]
想写个小工具 想把后端代码 也打包进去

**Comment by umbrella22** [comment]
参考之前的老的版本改吧，不过不推荐了，因为无论怎么样都不太需要服务端，除非你想做局域网伺服器
