### ISSUE TITLE
mini-main分支 package.json里面del重复 & .electron-vite/build.ts中 `const { clean = false, target = "client" } = getArgv();` 重复

### ISSUE THREAD

**Issue by huxianc** [umbrella22/electron-vite-template#144]
## package.json
- https://github.com/umbrella22/electron-vite-template/blob/mini-main/package.json#L39
- https://github.com/umbrella22/electron-vite-template/blob/mini-main/package.json#L40
## .electron-vite/build.ts
- https://github.com/umbrella22/electron-vite-template/blob/mini-main/.electron-vite/build.ts#L13
- https://github.com/umbrella22/electron-vite-template/blob/mini-main/.electron-vite/build.ts#L17

**Comment by mlmdflr** [comment]
感谢您的细心，我已经移除重复代码并且提交了
