### ISSUE TITLE
windows：用打包好的安装包安装后，启动报错！

### ISSUE THREAD

**Issue by x-skywalker** [umbrella22/electron-vite-template#17]
![image](https://user-images.githubusercontent.com/13618197/129736008-0cb9ef99-33bc-403a-959a-ed2389566af3.png)

**Comment by umbrella22** [comment]
已修

**Comment by umbrella22** [comment]
但是= =如果您能提供一下报错的计算机的环境信息，就再好不过了，这有助于确定根源 @x-skywalker

**Comment by x-skywalker** [comment]
> 但是= =如果您能提供一下报错的计算机的环境信息，就再好不过了，这有助于确定根源 @x-skywalker

Windows 10 家庭中文版 64位

**Comment by umbrella22** [comment]
@x-skywalker 嗯，目标计算机有node环境吗这类的。。。

**Comment by x-skywalker** [comment]
> @x-skywalker 嗯，目标计算机有node环境吗这类的。。。

有的，重新打包了，不报错了
