### ISSUE TITLE
函数式路由跳转问题咨询

### ISSUE THREAD

**Issue by WeMissing** [umbrella22/electron-vite-template#18]
您好!
 
    这两天在使用这个框架时遇到一个问题：

router==>constantRouterMap.ts路由配置如下：
const routes: Array<RouteRecordRaw> = [
    { path: '/:pathMatch(.*)*', component: () => import("@renderer/views/404.vue") },//@renderer/components/LandingPage.vue
    { path: '/', name: '登陆', component: () => import('@renderer/views/Login.vue') },
	{ path: '/main', name: '主页', component: () => import('@renderer/views/Main.vue') },
]

我在Login.vue里登陆认证成功后，要跳转到Main.vue，在登陆函数写的路由代码如下：
import router from '../router'

	  //router.replace('/main');//登陆成功跳转到首页
	  router.push({ path: 'main',replace:true })

调试工具控制台显示路由已经成功，且也走到了：router.afterEach(() => {
	console.log("页面跳转完整")
})
但是Main.vue页面内容并未显示，需要按F5刷新页面才显示出这个页面内容。

还请指导一下！

**Comment by umbrella22** [comment]
# 问题已定位，等待下个版本
