### ISSUE TITLE
Error: Cannot find module './rollup.Main.config'

### ISSUE THREAD

**Issue by dongasai** [umbrella22/electron-vite-template#32]
linux 下打包出错 ,能够运行，点击更新报错

node版本 v16.13.0
yarn版本 1.22.15

执行命令 `yarn build`

**Comment by umbrella22** [comment]
emmm，能提供一份截图吗....

**Comment by dongasai** [comment]
![1638254313878](https://user-images.githubusercontent.com/16734530/143998160-f40231a0-40ab-4c8d-a0f4-c563333895b0.png)

**Comment by umbrella22** [comment]
okk~最快一个小时以内修复~~

**Comment by umbrella22** [comment]
@dongasai 已修
