### ISSUE TITLE
在mac上打包win:32和win:64，有报错，打包mac正常

### ISSUE THREAD

**Issue by bbcrBBCR** [umbrella22/electron-vite-template#35]
⨯ /Users/admin/Library/Caches/electron-builder/nsis/nsis-3.0.4.2/mac/makensis exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Output:
Command line defined: "APP_ID=org.sky.electron-vite-template"
Command line defined: "APP_GUID=ddc7aa95-3ed7-5356-91ec-1d62657cfcd6"
Command line defined: "UNINSTALL_APP_KEY=ddc7aa95-3ed7-5356-91ec-1d62657cfcd6"
Command line defined: "PRODUCT_NAME=electron-vite-template"
Command line defined: "PRODUCT_FILENAME=electron-vite-template"
Command line defined: "APP_FILENAME=electron-vite-template"
Command line defined: "APP_DESCRIPTION="
Command line defined: "VERSION=1.0.0"
Command line defined: "PROJECT_DIR=/Users/admin/Workspace/github/electron-vite-template"
Command line defined: "BUILD_RESOURCES_DIR=/Users/admin/Workspace/github/electron-vite-template/build"
Command line defined: "APP_PACKAGE_NAME=electron-vite-template"
Command line defined: "MUI_ICON=/Users/admin/Workspace/github/electron-vite-template/build/icons/icon.ico"
Command line defined: "MUI_UNICON=/Users/admin/Workspace/github/electron-vite-template/build/icons/icon.ico"
Command line defined: "APP_32=/Users/admin/Workspace/github/electron-vite-template/build/electron-vite-template-1.0.0-ia32.nsis.7z"
Command line defined: "APP_32_NAME=electron-vite-template-1.0.0-ia32.nsis.7z"
Command line defined: "APP_32_HASH=AC515DFEAD36BA5741AFEBEA2F3D238A2A1A9E78A4352221E09FCF7E70500C7BD3F284FF65D81819D482EAB0091E522112A00501F12E825E7D2CDE3BEDB6455D"
Command line defined: "COMPANY_NAME=sky"
Command line defined: "APP_INSTALLER_STORE_FILE=electron-vite-template-updater\installer.exe"
Command line defined: "COMPRESSION_METHOD=7z"
Command line defined: "ONE_CLICK"
Command line defined: "RUN_AFTER_FINISH"
Command line defined: "SHORTCUT_NAME=electron-vite-template"
Command line defined: "UNINSTALL_DISPLAY_NAME=electron-vite-template 1.0.0"
Command line defined: "ESTIMATED_SIZE=174328"
Command line defined: "COMPRESS=auto"
Command line defined: "BUILD_UNINSTALLER"
Command line defined: "UNINSTALLER_OUT_FILE=Z:\Users\admin\Workspace\github\electron-vite-template\build\__uninstaller-nsis-electron-vite-template.exe"
Processing script file: "<stdin>" (UTF8)
Plugin directories:
  /Users/admin/Library/Caches/electron-builder/nsis/nsis-3.0.4.2/Plugins/x86-unicode

Error output:
Plugin not found, cannot call StdUtils::TestParameter
Error in macro _StdU_TestParameter on macroline 2
Error in macro _isUpdated on macroline 1
Error in macro _If on macroline 9
Error in macro _CHECK_APP_RUNNING on macroline 3
Error in macro CHECK_APP_RUNNING on macroline 4
!include: error in script: "uninstaller.nsh" on line 2
Error in script "<stdin>" on line 168 -- aborting creation process
  failedTask=build stackTrace=Error: /Users/admin/Library/Caches/electron-builder/nsis/nsis-3.0.4.2/mac/makensis exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Output:
Command line defined: "APP_ID=org.sky.electron-vite-template"
Command line defined: "APP_GUID=ddc7aa95-3ed7-5356-91ec-1d62657cfcd6"
Command line defined: "UNINSTALL_APP_KEY=ddc7aa95-3ed7-5356-91ec-1d62657cfcd6"
Command line defined: "PRODUCT_NAME=electron-vite-template"
Command line defined: "PRODUCT_FILENAME=electron-vite-template"
Command line defined: "APP_FILENAME=electron-vite-template"
Command line defined: "APP_DESCRIPTION="
Command line defined: "VERSION=1.0.0"
Command line defined: "PROJECT_DIR=/Users/admin/Workspace/github/electron-vite-template"
Command line defined: "BUILD_RESOURCES_DIR=/Users/admin/Workspace/github/electron-vite-template/build"
Command line defined: "APP_PACKAGE_NAME=electron-vite-template"
Command line defined: "MUI_ICON=/Users/admin/Workspace/github/electron-vite-template/build/icons/icon.ico"
Command line defined: "MUI_UNICON=/Users/admin/Workspace/github/electron-vite-template/build/icons/icon.ico"
Command line defined: "APP_32=/Users/admin/Workspace/github/electron-vite-template/build/electron-vite-template-1.0.0-ia32.nsis.7z"
Command line defined: "APP_32_NAME=electron-vite-template-1.0.0-ia32.nsis.7z"
Command line defined: "APP_32_HASH=AC515DFEAD36BA5741AFEBEA2F3D238A2A1A9E78A4352221E09FCF7E70500C7BD3F284FF65D81819D482EAB0091E522112A00501F12E825E7D2CDE3BEDB6455D"
Command line defined: "COMPANY_NAME=sky"
Command line defined: "APP_INSTALLER_STORE_FILE=electron-vite-template-updater\installer.exe"
Command line defined: "COMPRESSION_METHOD=7z"
Command line defined: "ONE_CLICK"
Command line defined: "RUN_AFTER_FINISH"
Command line defined: "SHORTCUT_NAME=electron-vite-template"
Command line defined: "UNINSTALL_DISPLAY_NAME=electron-vite-template 1.0.0"
Command line defined: "ESTIMATED_SIZE=174328"
Command line defined: "COMPRESS=auto"
Command line defined: "BUILD_UNINSTALLER"
Command line defined: "UNINSTALLER_OUT_FILE=Z:\Users\admin\Workspace\github\electron-vite-template\build\__uninstaller-nsis-electron-vite-template.exe"
Processing script file: "<stdin>" (UTF8)
Plugin directories:
  /Users/admin/Library/Caches/electron-builder/nsis/nsis-3.0.4.2/Plugins/x86-unicode
                                                                                            Error output:
Plugin not found, cannot call StdUtils::TestParameter
Error in macro _StdU_TestParameter on macroline 2
Error in macro _isUpdated on macroline 1
Error in macro _If on macroline 9
Error in macro _CHECK_APP_RUNNING on macroline 3
Error in macro CHECK_APP_RUNNING on macroline 4
!include: error in script: "uninstaller.nsh" on line 2
Error in script "<stdin>" on line 168 -- aborting creation process
at ChildProcess.<anonymous> (/Users/admin/Workspace/github/electron-vite-template/node_modules/builder-util/src/util.ts:250:14)
    at Object.onceWrapper (node:events:510:26)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)

**Comment by umbrella22** [comment]
不建议再macos上打包win端，因为builder依赖于nsis，该软件可能会因为macos端wine缺失一些东西导致打包失败

**Comment by bbcrBBCR** [comment]
好的，我晚点找一个window机器试一试是否可以

**Comment by bbcrBBCR** [comment]
昨晚用windows打包成功了，今天用虚拟机也ok的
