### ISSUE TITLE
__vite-browser-external:path:3 Uncaught Error: Module "path" has been externalized for browser compatibility and  cannot be accessed in client code.

### ISSUE THREAD

**Issue by kingdream123** [umbrella22/electron-vite-template#38]
在渲染层代码，引用 path 模块报错
请教下，这个怎么解决呀

完整错误信息如下：
__vite-browser-external:path:3 Uncaught Error: Module "path" has been externalized for browser compatibility and 
cannot be accessed in client code.
    at Object.get (__vite-browser-external:path:3)
    at FileBufferTransport._createStream (file.ts:46)
    at FileBufferTransport.reload (file.ts:28)
    at new FileTransport (file.ts:16)

**Comment by umbrella22** [comment]
不建议再渲染进程使用任何node模块，建议使用ipc或者严格分支的preload方案

**Comment by kingdream123** [comment]
> 

ok，本来想偷懒一把梭😄，最后还是用preload方案来做了
