### ISSUE TITLE
请问大大，我使用了typeORM，要用到装饰器，但是编译报错

### ISSUE THREAD

**Issue by kingdream123** [umbrella22/electron-vite-template#39]
请问大大，我使用了typeORM，要用到装饰器，但是编译报错。
试验了几个插件都不行，麻烦问下，这个有简便的修改方案没~

**Comment by umbrella22** [comment]
![渲染进程](https://user-images.githubusercontent.com/19886152/149114386-9affae80-3cde-403d-b730-2e47a984d88b.png)
![主进程](https://user-images.githubusercontent.com/19886152/149114604-4ac87c5d-5818-42d0-b2fb-11193d775bb2.png)

丫吼~很抱歉现在才回复你，但是在我这里测是可以使用的哦，渲染进程和主进程都可以使用哦，如果方便的话，还请带上截图哦

**Comment by kingdream123** [comment]
我提交了一个测试Demo，麻烦大大，帮忙看下 ღ( ´･ᴗ･` )
[TypeORM-Demo](https://github.com/kingdream123/electron-vite-template)
相关代码目录：src/main/database/

相关代码截图，是在主进程
![orm-0](https://user-images.githubusercontent.com/14135124/149120227-55ed58d0-0d76-4515-b805-c5f104eb11ef.png)
![orm-2](https://user-images.githubusercontent.com/14135124/149120270-335a5d23-ad5c-4b1c-b192-1036cb778879.png)
![orm-3](https://user-images.githubusercontent.com/14135124/149120903-a0e4e1b2-2b4a-423c-b9fb-392ae8d2a50f.png)

**Comment by umbrella22** [comment]
emm........它看起来并不是不支持装饰器导致的，而是您的@Column装饰器参数少了一些导致报错了~如下图所示即可：

![image](https://user-images.githubusercontent.com/19886152/149139903-5f99d83c-ebe0-47e3-a6f5-be8a1101a915.png)

> 这个报错看起来是无法推断出您装饰器下面的变量类型导致的，您需要手动指定type即可。

**Comment by kingdream123** [comment]
感谢大佬指点~
我看TypeORM的文档，@Column 不指定type时，默认会自动取变量类型呢，string 自动对应 varchatr  ＞﹏＜
非常感谢~~

**Comment by umbrella22** [comment]
emm，那就不知道了~~~但是这里看起来是必须要的~~那我就关issues啦~
