### ISSUE TITLE
为什么你的主进程里导入模块可以使用`import {app} from 'electron';`,需要对主进程进行什么配置吗？

### ISSUE THREAD

**Issue by helptome1** [umbrella22/electron-vite-template#41]
为什么你的主进程里导入模块可以使用`import {app} from 'electron';`,需要对主进程进行什么配置吗？

**Comment by umbrella22** [comment]
你这个问的我一时间就不知道该怎么回答了.....因为 **我的主进程经过编译了啊，你没发现我的主进程还是ts吗？**

**Comment by dest1n1s** [comment]
想请教一下为何在渲染进程中可以使用```const { ipcRenderer } = require('electron')```而不能使用```import { ipcRenderer } from 'electron'```？后者会报错```path.join is not a function```。

我猜测可能是因为```path```包是 node 专有的，但我依然不太理解为何 ```require``` 不会引发这一问题。

**Comment by umbrella22** [comment]
@dest1n1s 你猜测的没错，因为vite会接管import行为，对于vite而言，它没有处理原生依赖的能力，所以需要使用require去规避

**Comment by dest1n1s** [comment]
明白了，感谢大佬解答！
