### ISSUE TITLE
目前包这里需要怎样协调，我这里的提示如下

### ISSUE THREAD

**Issue by wzskyline** [umbrella22/electron-vite-template#43]
electron-vite-template>npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: electron-vite-template@1.0.0
npm ERR! Found: javascript-obfuscator@4.0.0
npm ERR! node_modules/javascript-obfuscator
npm ERR!   dev javascript-obfuscator@"^4.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer javascript-obfuscator@"^0.18.1" from rollup-plugin-obfuscator@0.2.1
npm ERR! node_modules/rollup-plugin-obfuscator
npm ERR!   dev rollup-plugin-obfuscator@"^0.2.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\wzskyline\AppData\Local\npm-cache\eresolve-report.txt for a full report.

**Comment by umbrella22** [comment]
![image](https://user-images.githubusercontent.com/19886152/160567310-cff77045-1c3c-407f-91e9-1850c0e9cbe2.png)
奇怪我并没有让你使用npm去安装吧。。
