### ISSUE TITLE
Maybe we could use the official `@vue/devtools` package?

### ISSUE THREAD

**Issue by yzqdev** [umbrella22/electron-vite-template#46]
作者大大您的这个模板里面用的是`electron-devtools-vendor`这个包来引入devtools,但是这个包的作者不一定能及时把devtools更新到最新版,所以一些旧版本devtools的bug还在(已经遇到过了).  
而现在官方发布了`@vue/devtools`的`Standalone` 版本,可以直接在electron上使用,并发布在了npm,可以及时更新,文档如下
https://devtools.vuejs.org/guide/installation.html#using-dependency-package

不知大佬意见如何?

**Comment by umbrella22** [comment]
喔！这个嘛可以啊，不过我可能得有时间才去迁移了，如果你已经做完这方面的工作的话，我也欢迎pr哦~~

**Comment by yzqdev** [comment]
啊,很抱歉这么晚才回复,用官方的`@vue/devtools`其实很简单的,就全局安装下`@vue/devtools`后运行,然后在渲染进程的index.html加一行代码就行.  
不过嘛,这个`Standalone`版本的devtools包是一个electron应用,有一个单独的页面,不是集成在`chrome devtool`上的,而且启动的话也会多占两三百兆的内存,不是很舒服,所以感觉换不换无所谓了😂

**Comment by umbrella22** [comment]
噗哈哈哈，那算啦，如果它还要在启动一个electron那就得不偿失了

**Comment by xiaohong-yang** [comment]
这个问题现在还没解决 ，我看已经 electron-devtools-vendor v2.1.0已经是最新版本，vue-devtools根本无法使用

**Comment by umbrella22** [comment]
@xiaohong-yang 没办法，这个需要上游解决，我猜测是因为electron的Chromium版本过高，而插件又没有兼容导致的
