### ISSUE TITLE
页面dom不会被释放

### ISSUE THREAD

**Issue by xiaozxz** [umbrella22/electron-vite-template#49]
在页面上加了一个普通的组件，内容大致如下
<template>
  <div>
    <div v-for="(item, i) in arr" :key="i"></div>
  </div>
</template>

<script lang="ts" setup>
 const arr = new Array(1000).join("x").split("x");
</script>

页面上搞了个路由不断切换进去，内存尽然不释放，大佬能帮忙排查一下原因不

**Comment by umbrella22** [comment]
= =.........对此我只能说，路由切换不代表会立刻回收不使用的变量，这涉及到js的内存回收机制，按理来说应该会出现波形图一样的回收，如果你想内存立刻回收应该手动置空。。。而且还有，你这个没有抛到dom，是属于js中变量....
