### ISSUE TITLE
There is a bug: top bar hide content

### ISSUE THREAD

**Issue by DoMoCo** [umbrella22/electron-vite-template#58]
In the full screen state, the top menu bar retains a white bar and hides the content.
See the picture for the details:
<img width="1512" alt="截屏2022-07-19 15 50 04" src="https://user-images.githubusercontent.com/22541710/179697682-ff1eb6bb-bfa7-4123-bda3-9e2070c40ab8.png">

**Comment by umbrella22** [comment]
emm，I observed that your white edge is just the customized head height. I think you can delete the `<title-bar/>` component in the app.vue file to solve this problem
