### ISSUE TITLE
DisableF12属性不存在

### ISSUE THREAD

**Issue by Helius-web** [umbrella22/electron-vite-template#59]
![image](https://user-images.githubusercontent.com/81142448/183352781-2329c79b-b4b0-43a9-ad3e-7117ff7270b7.png)
src/main/config/DisableButton.ts
![image](https://user-images.githubusercontent.com/81142448/183352973-ea60084f-095e-4370-8386-d284f48b0025.png)
config/index.ts
DisableF12有点小问题(strict也存在)

**Comment by umbrella22** [comment]
啊...忘记加上build对象了，可能是之前改的时候遗漏了，emm后面来修
