### ISSUE TITLE
三方依赖引入的问题

### ISSUE THREAD

**Issue by dwfrost** [umbrella22/electron-vite-template#62]
我打算做一个小程序自动上传的桌面应用，其中有用到`miniprogram-ci`这个npm包。

1. 将`miniprogram-ci`安装在`devDependencies`下
   `npm i miniprogram-ci -D`

2. 然后在LandingPage.vue中引入
   const ci = require('miniprogram-ci')
   console.log('ci',ci)
   则会出现：
   - 开发环境正常，可以正常使用。
   - 打包应用后，发现加载失败，表现为白屏。

环境：
- windows10 64位系统
- node v14.18.1
- npm 6.14.15

**Comment by umbrella22** [comment]
这个应该是一个node依赖，我建议是安装到 `dependencies` 中，按你的描述我觉得打包以后白屏应该控制台应该还报错找不到这个包

**Comment by dwfrost** [comment]
> 

是依赖了path等Node变量，放到dependencies打包可以正常使用，可是它太大了，全部打包需要10分钟+。我找找其他方案
