### ISSUE TITLE
建议增加 vite-plugin-electron-renderer

### ISSUE THREAD

**Issue by Sailiy** [umbrella22/electron-vite-template#64]
建议增加vite-plugin-electron-renderer插件可以在渲染进程nodejs API

**Comment by umbrella22** [comment]
emm，这个请容我拒绝，这个架子的严格分支是后期的更新趋势，将会逐步收紧在渲染进程中使用node的能力

**Comment by umbrella22** [comment]
emm，这个请容我拒绝，这个架子的严格分支是后期的更新趋势，将会逐步收紧在渲染进程中使用node的能力
