### ISSUE TITLE
yarn build报错

### ISSUE THREAD

**Issue by Niaddice** [umbrella22/electron-vite-template#73]
(!) Some chunks are larger than 500 KiB after minification. Consider:
- Using dynamic import() to code-split the application
✔ building main process
✔ building renderer process
  ›  OKAY  take it away `electron-builder`
  • electron-builder  version=23.3.3 os=22.1.0
  • loaded configuration  file=/Users/nijiabin/code/WebstormProjects/electron-vite-template/build.json
  • writing effective config  file=build/builder-effective-config.yaml
  • packaging       platform=darwin arch=arm64 electron=18.3.5 appOutDir=build/mac-arm64
Error: Command failed: electron /Users/nijiabin/code/WebstormProjects/electron-vite-template/.electron-vite/bytecode/electron-compiler.js
    at checkExecSyncError (node:child_process:841:11)
    at execSync (node:child_process:912:15)
    at /Users/nijiabin/code/WebstormProjects/electron-vite-template/.electron-vite/builderHook/byteCodeHook.js:22:9
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

大佬，这是什么问题

**Comment by umbrella22** [comment]
#74 已解决

**Comment by Niaddice** [comment]
重拉了最新的，还是这个错误

**Comment by umbrella22** [comment]
再试试呢 #76

**Comment by Niaddice** [comment]
OK了，🙏辛苦
