### ISSUE TITLE
discord channel

### ISSUE THREAD

**Issue by Meguais** [umbrella22/electron-vite-template#81]
hi 
we can share our information, problems, is there a discord channel

**Comment by umbrella22** [comment]
This may be related to the yarn.lock file, you can try deleting the yarn.lock file in the root directory of the project and then re-executing the yarn install command, which may help. Or I see that you are using PowerShell, you can also try to press Enter once, as this may be a mouse click to select PowerShell causing it to be suspended. Typically, this step should not take more than 30 minutes, but it depends on your network and computer performance

**Comment by umbrella22** [comment]
Ah, sorry this is my problem, will fix it soon. 
QAQ
