### ISSUE TITLE
can i remove expressjs server file ?

### ISSUE THREAD

**Issue by Meguais** [umbrella22/electron-vite-template#83]
I get an error when I delete the server folder how can I fix this express what exactly will it do for me

**Comment by umbrella22** [comment]
Sure, you need the following steps

1. Run yarn remove express to remove express dependency
2. Delete the `src/main/server` folder
3. In the `src/main/services/ipcMain.ts` file and remove the `import server from "../server"` Then remove the code shown in the figure below and express will be completely removed
---
![file](https://user-images.githubusercontent.com/19886152/210202245-a40f0594-c848-4003-baab-e6e37ec645ce.png)
---
I'm sorry that there is no smallest example. This part of the work will be carried out in the near future

**Comment by Meguais** [comment]
thank you and i have one more question how can i setup updaters any one have documents?
