### ISSUE TITLE
hi can u help me how can i add when show ready

### ISSUE THREAD

**Issue by Meguais** [umbrella22/electron-vite-template#84]
I want a loading page I couldn't do it for the 2nd window how do I redirect it

**Comment by umbrella22** [comment]
emm, there is already a loading page in this project, it will load the loading .html in the `static` folder, and will show your rendering process when the second page is ready, I don't quite understand what you are trying to say, you can't redirect the interface of the rendering process?

**Comment by Meguais** [comment]
![image](https://user-images.githubusercontent.com/47488328/212458136-c28ab932-4366-4739-9a11-be007fcbb94b.png)

**Comment by Meguais** [comment]
i can see the white page

**Comment by umbrella22** [comment]
Emm, I don't know why you can only see your reply from the email. On the white screen, I guess the path you loaded is incorrect or you used some libraries that were not loaded correctly. You can use electron-log to print to see if your path is correct, or you can open the browser console to check if there is any error message on the console
- Open the devtools code after packaging, as shown below
**In the `src\main\config\windowsConfig.ts`**
```typescript
export const mainWindowConfig: BrowserWindowConstructorOptions = {
    height: 800,
    useContentSize: true,
    width: 1700,
    minWidth: 1366,
    show: false,
    frame: config.IsUseSysTitle,
    webPreferences: {
        contextIsolation: false,
        nodeIntegration: true,
        webSecurity: false,
        // Modify this to true
        devTools: true,
        scrollBounce: process.platform === 'darwin',
    }
};
```
**In the `src\main\services\windowManager.ts`**
```typescript
    this.mainWindow.once('ready-to-show', () => {
      this.mainWindow.show()
      // Delete judgment here
      // if (process.env.NODE_ENV === 'development') {
        this.mainWindow.webContents.openDevTools({ mode: 'undocked', activate: true })
      // }
      if (config.UseStartupChart) this.loadWindow.destroy()
    })
```
So you can see devtools. If there is no display in devtools, including dom element, you need to use electron-log to print whether the url path of mainWindow is correct
