### ISSUE TITLE
点击增量更新(第二种) 按钮后，在进度条走动过程中，关闭主窗口，会额外弹出错误

### ISSUE THREAD

**Issue by zwwsun** [umbrella22/electron-vite-template#86]
![企业微信截图_1675414481150](https://user-images.githubusercontent.com/29347565/216556509-53a3f5cd-b185-42aa-9737-4a270361838e.png)

**Comment by zwwsun** [comment]
$ node -v
v18.12.0

$ npm -v
8.19.2

**Comment by umbrella22** [comment]
如果是增量更新的话，你得在打包以后在执行剩下的操作，不然就会出现这种情况
