### ISSUE TITLE
i update  your template and install and  I reinstalled dont show public/loader.html

### ISSUE THREAD

**Issue by Meguais** [umbrella22/electron-vite-template#89]
i update  your template and install and  I reinstalled dont show public/loader.html

**Comment by Meguais** [comment]
![image](https://user-images.githubusercontent.com/47488328/226099461-c205121c-b478-4d6f-85f4-ca3799d91efa.png)
and i get some error

**Comment by umbrella22** [comment]
I'm sorry for replying so late. I have fixed this issue
