### ISSUE TITLE
为什么vue、element-plus 等包要放到devDependencies，不是放到dependencies里么，另外，typescript不熟悉的话，可以直接使用javascript开发么

### ISSUE THREAD

**Issue by 593496637** [umbrella22/electron-vite-template#90]

**Comment by umbrella22** [comment]
emm，可以使用js开发，但是不推荐，因为你会使用js的一些魔法内容导致错误无法正常定位，vue、element-plus这些东西在打包以后就不再需要，他们包含在产物中，所以没有必要放在dependencies中，那样会被builder打包进最终产物的node_modules文件夹中，会增大体积而且没有任何意义
