### ISSUE TITLE
编译后不能运行，提示缺少模块

### ISSUE THREAD

**Issue by gkey02** [umbrella22/electron-vite-template#93]
更新后编译，没有处理依赖包，依赖的包没有打包，运行时提示缺少依赖模块。
我没研究该项目的打包原理，依赖处理不应该是打包程序处理的吗，不知道为啥会存在这种错误。

**Comment by umbrella22** [comment]
emm，不太明白缺少依赖包的意思，有截图吗

**Comment by gkey02** [comment]
emm，抱歉呢，仔细读了一遍可能确实没表达清楚，那个就是生成的exe包没有解析深度依赖，只拷贝了package.json添加的包，附图：

<img width="1487" alt="微信截图_20230422004539" src="https://user-images.githubusercontent.com/20350048/233690981-ab02d221-d754-4898-8a2d-a5bb818d6dab.png">

<img width="1421" alt="微信截图_20230422004608" src="https://user-images.githubusercontent.com/20350048/233691046-15c1e216-75da-4ea8-becd-568df4489da4.png">

**Comment by umbrella22** [comment]
emm这个稍后我使用windows系统看一看吧，macos上并没有复现这个问题，当然如果可以的话，请使用yarn作为这个项目的包管理器，pnpm因为我没有为它创建lock文件，可能会因为一些依赖更新导致该问题

**Comment by umbrella22** [comment]
很抱歉我在windows中也没有复现该问题，暂时关闭该问题，若有相同问题请重新开启
